version: '3.9'

services:
  nginx:
    container_name: nginx
    platform: linux/arm64v8
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - wordpress_data:/var/www/html
      - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/nginx/wordpress-prod.conf:/etc/nginx/conf.d/wordpress-prod.conf
    depends_on:
      - wordpress
      - mariadb
    networks:
      - totoronet

  mariadb:
    container_name: mariadb
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - totoronet

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: wordpress.prod.dockerfile
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WP_ENVIRONMENT_TYPE: ${WP_ENVIRONMENT_TYPE}
      S3_UPLOADS_USE_LOCAL: ${S3_UPLOADS_USE_LOCAL}
      S3_UPLOADS_USE_INSTANCE_PROFILE: ${S3_UPLOADS_USE_INSTANCE_PROFILE}
      S3_UPLOADS_REGION: ${S3_UPLOADS_REGION}
      S3_UPLOADS_BUCKET: ${S3_UPLOADS_BUCKET}
      S3_UPLOADS_KEY: ${S3_UPLOADS_KEY}
      S3_UPLOADS_SECRET: ${S3_UPLOADS_SECRET}
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - totoronet

volumes:
  mariadb_data:
  wordpress_data:


networks:
  totoronet:
