version: '3.9'

services:
  nginx:
    container_name: nginx
    platform: linux/arm64v8
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/nginx/wordpress-prod.conf:/etc/nginx/conf.d/wordpress-prod.conf
    depends_on:
      - wordpress
      - mariadb
    networks:
      - mysitenet

  mariadb:
    container_name: mariadb
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mysitenet

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: wordpress.prod.dockerfile
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: wordpress
      WORDPRESS_ADMIN_EMAIL: "wordpress@totoro.docker"
      WP_ENVIRONMENT_TYPE: local
      S3_UPLOADS_USE_LOCAL: "true"
      S3_UPLOADS_USE_INSTANCE_PROFILE: "false"
      S3_UPLOADS_REGION: ""
      S3_UPLOADS_BUCKET: ""
      SERVER_NAME: "raspberrypi.local"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mysitenet

volumes:
  mariadb_data:
  wordpress_data:


networks:
  mysitenet:
