version: '3.9'

services:
  nginx:
    container_name: nginx
    platform: linux/arm64v8
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/nginx/wordpress-prod.conf:/etc/nginx/conf.d/wordpress-prod.conf
      - ./bin/certs:/etc/nginx/certs/self-signed/
    depends_on:
      - wordpress
      - mysqldb
    networks:
      - mysitenet

  mysqldb:
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    restart: always
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      - mysitenet

  wordpress:
    build:
      context: .
      dockerfile: wordpress.prod.dockerfile
    restart: always
    depends_on:
      - mysqldb
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WP_ENVIRONMENT_TYPE: local
      S3_UPLOADS_USE_LOCAL: "true"
      S3_UPLOADS_USE_INSTANCE_PROFILE: "false"
      S3_UPLOADS_REGION: ""
      S3_UPLOADS_BUCKET: ""
      SERVER_NAME: "raspberrypi.local"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mysitenet

volumes:
  mysqldb_data:
  wordpress_data:


networks:
  mysitenet:
