services:
  nginx:
    container_name: nginx
    platform: linux/arm/v7
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/nginx/wordpress-prod.conf:/etc/nginx/conf.d/wordpress-prod.conf
    depends_on:
      - wordpress
      - mariadb

  mariadb:
    container_name: mariadb
    image: jsurf/rpi-mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oxbuild
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      SERVICE_NAME: mariadb
      SERVICE_TAGS: local
    volumes:
      - database:/var/lib/mysql

  wordpress:
    container_name: wordpress
    platform: linux/arm/v7
    user: $UID:$GID
    build:
      context: .
      dockerfile: wordpress.prod.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./opt/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: wordpress
      WORDPRESS_ADMIN_EMAIL: "wordpress@totoro.docker"
      WP_ENVIRONMENT_TYPE: local
      S3_UPLOADS_USE_LOCAL: "true"
      S3_UPLOADS_USE_INSTANCE_PROFILE: "false"
      S3_UPLOADS_REGION: ""
      S3_UPLOADS_BUCKET: ""
      SERVER_NAME: "totoro.casa"

volumes:
  database:
    driver: local
