# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: totoro-ms-build-{{ .Values.env }}
type: Opaque
data:
  # Base64 encode your secrets.
  dbUser: d29yZHByZXNzX3VzZXI=             # 'wordpress_user'
  dbPassword: c2VjdXJlcGFzc3dvcmQ=         # 'securepassword'
  dbName: d29yZHByZXNzX2Ri                  # 'wordpress_db'
  adminUser: YWRtaW4=                      # 'admin'
  adminPassword: YWRtaW5wYXNz              # 'adminpass'
  adminEmail: YWRtaW5AZXhhbXBsZS5jb20=     # 'admin@example.com'
  wpEnvironmentType: cHJvZHVjdGlvbg==      # 'production'
