apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: totoro-ms-build-{{ .Values.env }}
  labels:
    app: wordpress-stack
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: wordpress-stack
  type: ClusterIP
