# values.yaml
domain: totoro-ox.net

env: prod

image:
  nginx:
    repository: nginx
    tag: latest
  wordpress:
    repository: wordpress
    tag: latest
  mariadb:
    repository: jsurf/rpi-mariadb
    tag: latest

mysql:
  rootPassword: root_password
  database: wordpress_db
  user: wordpress_user
  password: wordpress_password

wordpress:
  dbHost: mariadb
  adminUser: admin
  adminPassword: admin_password
  adminEmail: admin@example.com

persistence:
  enabled: true
  storageClass: "manual"
  accessMode: ReadWriteOnce
  size: 5Gi

secrets:
  MULTISITE: "true"
  WP_ALLOW_MULTISITE: "true"
  BLOG_ID_CURRENT_SITE: "1"
  SITE_ID_CURRENT_SITE: "1"
  SUBDOMAIN_INSTALL: "false"
  DOMAIN_CURRENT_SITE: "totoro-ox.net"
  COOKIE_DOMAIN: "false"
  ADMIN_COOKIE_PATH: "/"
  COOKIEPATH: "/"
  SITECOOKIEPATH: "/"
  WP_ENVIRONMENT_TYPE: "prod"
  AUTOMATIC_UPDATER_DISABLED: "true"
  FORCE_SSL_ADMIN: "false"
  S3_UPLOADS_BUCKET: ""
  S3_UPLOADS_REGION: ""
  S3_UPLOADS_KEY: ""
  S3_UPLOADS_SECRET: ""
  S3_UPLOADS_USE_INSTANCE_PROFILE: ""
  QM_ENABLE_CAPS_PANEL: "true"
  WP_CACHE: "true"
  dbUser: "wordpress_user"
  dbPassword: "securepassword"
  dbName: "wordpress_db"
  adminUser: "admin"
  adminPassword: "adminpass"
  adminEmail: "admin@example.com"
  wpEnvironmentType: "production"


