domain: "${DOMAIN}"
env: "${ENV}"

image:
  nginx:
    repository: "${IMAGE_NGINX_REPOSITORY}"
    tag: "${IMAGE_NGINX_TAG}"
  wordpress:
    repository: "${IMAGE_WORDPRESS_REPOSITORY}"
    tag: "${IMAGE_WORDPRESS_TAG}"
  mariadb:
    repository: "${IMAGE_MARIADB_REPOSITORY}"
    tag: "${IMAGE_MARIADB_TAG}"

mysql:
  rootPassword: "${MYSQL_ROOT_PASSWORD}"
  database: "${MYSQL_DATABASE}"
  user: "${MYSQL_USER}"
  password: "${MYSQL_PASSWORD}"

wordpress:
  dbHost: "${WORDPRESS_DB_HOST}"
  adminUser: "${WORDPRESS_ADMIN_USER}"
  adminPassword: "${WORDPRESS_ADMIN_PASSWORD}"
  adminEmail: "${WORDPRESS_ADMIN_EMAIL}"

persistence:
  enabled: "${PERSISTENCE_ENABLED}"
  storageClass: "${PERSISTENCE_STORAGE_CLASS}"
  accessMode: "${PERSISTENCE_ACCESS_MODE}"
  size: "${PERSISTENCE_SIZE}"

secrets:
  MULTISITE: "${SECRETS_MULTISITE}"
  WP_ALLOW_MULTISITE: "${SECRETS_WP_ALLOW_MULTISITE}"
  BLOG_ID_CURRENT_SITE: "${SECRETS_BLOG_ID_CURRENT_SITE}"
  SITE_ID_CURRENT_SITE: "${SECRETS_SITE_ID_CURRENT_SITE}"
  SUBDOMAIN_INSTALL: "${SECRETS_SUBDOMAIN_INSTALL}"
  DOMAIN_CURRENT_SITE: "${SECRETS_DOMAIN_CURRENT_SITE}"
  COOKIE_DOMAIN: "${SECRETS_COOKIE_DOMAIN}"
  ADMIN_COOKIE_PATH: "${SECRETS_ADMIN_COOKIE_PATH}"
  COOKIEPATH: "${SECRETS_COOKIEPATH}"
  SITECOOKIEPATH: "${SECRETS_SITECOOKIEPATH}"
  WP_ENVIRONMENT_TYPE: "${SECRETS_WP_ENVIRONMENT_TYPE}"
  AUTOMATIC_UPDATER_DISABLED: "${SECRETS_AUTOMATIC_UPDATER_DISABLED}"
  FORCE_SSL_ADMIN: "${SECRETS_FORCE_SSL_ADMIN}"
  S3_UPLOADS_BUCKET: "${SECRETS_S3_UPLOADS_BUCKET}"
  S3_UPLOADS_REGION: "${SECRETS_S3_UPLOADS_REGION}"
  S3_UPLOADS_KEY: "${SECRETS_S3_UPLOADS_KEY}"
  S3_UPLOADS_SECRET: "${SECRETS_S3_UPLOADS_SECRET}"
  S3_UPLOADS_USE_INSTANCE_PROFILE: "${SECRETS_S3_UPLOADS_USE_INSTANCE_PROFILE}"
  QM_ENABLE_CAPS_PANEL: "${SECRETS_QM_ENABLE_CAPS_PANEL}"
  WP_CACHE: "${SECRETS_WP_CACHE}"
