# values.yaml
domain: totoro-ox.net

env: prod

image:
  nginx:
    repository: nginx
    tag: latest
  wordpress:
    repository: wordpress
    tag: latest
  mariadb:
    repository: jsurf/rpi-mariadb
    tag: latest

mysql:
  rootPassword: root_password
  database: wordpress_db
  user: wordpress_user
  password: wordpress_password

wordpress:
  dbHost: mariadb
  adminUser: admin
  adminPassword: admin_password
  adminEmail: admin@example.com

persistence:
  enabled: true
  storageClass: "manual"
  accessMode: ReadWriteOnce
  size: 5Gi

