name: Deploy to PI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.KEY }}
        ssh-passphrase: ${{ secrets.PASSPHRASE }}

    - name: Copy repository to server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude=".git" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/usr/local/bin
