name: remote ssh command
on: [push]
jobs:

  build:
    name: Deploy to PI
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          mkdir -p /usr/local/bin/ox-build
          scp -r $GITHUB_WORKSPACE/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/usr/local/bin/ox-build